### ISSUE TITLE
Error when calling ``AppStat.max_downloads`` and ``AppStat.min_downloads``

### ISSUE THREAD

**Issue by vladcalin** [EternityPy/PlayStats#2]
Hello,
When playing with the example from README, I stumbled upon these errors:

```
>>> app.max_downloads()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/playstats/appstat.py", line 107, in max_downloads
    return int(match[0].text.split('-')[1].replace(',', ''))
IndexError: list index out of range
>>> app.min_downloads()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/playstats/appstat.py", line 97, in min_downloads
    return int(match[0].text.split('-')[0].replace(',', ''))
ValueError: invalid literal for int() with base 10: ' 1.000.000.000 â\x80\x93 5.000.000.000 '
```

I suppose it is needed a better error handling and values that cannot be extracted should default to ``None``.  
What do you think?

**Comment by apoorvaeternity** [comment]
@vladcalin Hey,
Can you tell me the package name that you were using?
Thanks for raising the issue.
And yeah None would be better as the default.

**Comment by vladcalin** [comment]
@apoorvaeternity The issue seems to be related to localisation.

When I am running this directly in the internet from my ISP provider (in Romania), I get the following result:

```
app = AppStat('com.whatsapp')
>>> app.max_downloads()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/playstats/appstat.py", line 107, in max_downloads
    return int(match[0].text.split('-')[1].replace(',', ''))
IndexError: list index out of range
```

But when I run it while I am connected to VPN through US, it works as expected

```
app = AppStat('com.whatsapp')
app.max_downloads()
# 5000000000
```

I don't think it is an issue that need to be addressed right now. Maybe you can find a way to force the Google play page to be returned in an english localisation?

**Comment by apoorvaeternity** [comment]
Yeah I haven't done anything to deal with the localisation yet.
I think forcing english localisation would be the best option for now if possible.
